# These are supported funding model platforms

#github: Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#patreon: Replace with a single Patreon username
#open_collective: Replace with a single Open Collective username
community_bridge: aebccbbb-2478-4817-af06-5d6475a98664
#liberapay: Replace with a single Liberapay username
custom: ['https://www.pwcq.dev/support/']
